language: java
jdk: oraclejdk8
notifications:
  email:
    recipients:
      - cafemgmt@gmail.com
      - krishanu.das2009@gmail.com
    on_success: never # default: change
    on_failure: always # default: always