# Team Yaml
coverage:
  round: down
  precision: 5

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 3
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no

codecov:
  token: 454e440d-dc48-4e0e-951c-3346c6a74ab8  

coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null
