# Team Yaml
coverage:
  round: down
  precision: 5

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach, diff, flags, files, footer"
  behavior: default
  require_changes: no
  
coverage:
  notify:
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        threshold: 0%
        only_pulls: false
        branches: null
        flags: null
        paths: null
